In [2]:
import pandas as pd
import numpy as np

In [2]:
!ls

2017-I.csv	  2017II.csv  2018II.csv    README.md
2017II-2018I.csv  2018I.csv   carreras.csv  Untitled.ipynb

In [3]:
df2017_2 = pd.read_csv("2017II.csv", sep=";")
carreras = pd.read_csv("carreras.csv")

In [90]:
lista_csvs = ["2017II.csv", "2018I.csv", "2018II.csv"]

In [101]:
dfs = [pd.read_csv(csv, sep=";") for csv in lista_csvs]

In [102]:
not_modify = ['nombre', 'matricula', 'genero', 'paralelo', 'cod_carrera']

In [103]:
dfs[0].columns

Index(['nombre', 'matricula', 'genero', 'paralelo', 'cod_carrera',
       'veces_tomadas', '1er_proyecto', '1er_sustent', '1er_lecciones',
       '1er_calif_final', '1er_exam_tema1', '1er_exam_tema2', '1er_exam_tema3',
       '1er_exam_tema4', '2do_proyecto', '2do_sustent', '2do_lecciones',
       '2do_calif_final', '2do_exam_tema1', '2do_exam_tema2', '2do_exam_tema3',
       'calif_final_practica', '3er_proyecto', '3er_calif_final',
       '3er_exam_tema1', '3er_exam_tema2', '3er_exam_tema3'],
      dtype='object')

In [104]:
dfs = [pd.read_csv(csv, sep=";") for csv in lista_csvs]

In [105]:
for df in dfs:
    df["veces_tomadas"] = df.veces_tomadas.fillna(1)
    for col in df.columns:
        if col not in not_modify:
            df[col] = df[col].astype(str)
            df[col] = df[col].str.replace(',', '.')
            df[col] = df[col].astype(float)
    df["veces_tomadas"] = df["veces_tomadas"].astype(int)

In [106]:
dfs_2017 = pd.read_csv("2017-I.csv", sep=";")

In [132]:
for df in dfs:
    columns = df.columns
    cols1ex = [col for  col in columns if "1er_exam_" in col]
    ex1_null = (np.all(df[cols1ex].isnull().values, axis = 1))
    print("Null ex1", ex1_null.sum())
    cols2ex = [col for  col in columns if "2do_exam_" in col]
    
    ex2_null = (np.all(df[cols2ex].isnull().values, axis = 1))
    print("Null ex2", ex2_null.sum())
    
    eq_0 = (df["1er_calif_final"].isnull() | df["2do_calif_final"].isnull()  | (df["1er_calif_final"] == 0) | 
          (df["2do_calif_final"] == 0))
    
    cols3ex = [col for  col in columns if "3er_exam_" in col]
    
    ex3_null = (np.all(df[cols3ex].isnull().values, axis = 1)) | df["3er_calif_final"].isnull() | (df["3er_calif_final"] == 0)
    print("Num eq0", eq_0.sum())
    print(df.isnull().sum())
    df["retirado"] = (eq_0 | ex1_null | ex2_null) & ex3_null & (~ df.AP)
    print("retirados:", df.retirado.sum())

Null ex1 35
Null ex2 211
Num eq0 103
nombre                      0
matricula                   0
genero                      0
paralelo                    0
cod_carrera                 0
veces_tomadas               0
1er_proyecto                7
1er_sustent                34
1er_lecciones              72
1er_calif_final             5
1er_exam_tema1             42
1er_exam_tema2             36
1er_exam_tema3             36
1er_exam_tema4             37
2do_proyecto               67
2do_sustent               116
2do_lecciones             108
2do_calif_final            32
2do_exam_tema1            212
2do_exam_tema2            213
2do_exam_tema3            219
calif_final_practica        9
3er_proyecto              740
3er_calif_final             0
3er_exam_tema1            567
3er_exam_tema2            596
3er_exam_tema3            604
retirado                    0
examen1                    44
examen2                   221
examen3                   605
final_sin_mejoramiento     40
final                      40
AP                          0
dtype: int64
retirados: 184
Null ex1 6
Null ex2 27
Num eq0 51
Unnamed: 0                  0
nombre                      0
matricula                   0
genero                      0
paralelo                    0
cod_carrera                 0
veces_tomadas               0
1er_proyecto                1
1er_sustent                 4
1er_lecciones               1
1er_calif_final             0
1er_exam_tema1              6
1er_exam_tema2              6
1er_exam_tema3              6
2do_proyecto                7
2do_sustent                 9
2do_lecciones               6
2do_calif_final             3
2do_exam_tema1             27
2do_exam_tema2             27
2do_exam_tema3             28
calif_final_practica        3
3er_proyecto              442
3er_calif_final             0
3er_exam_tema1            405
3er_exam_tema2            406
3er_exam_tema3            406
calif_final_100             3
calif_theoric_80            3
calif_practical_20          3
1er_exam                    6
2do_exam                   28
3er_exam                  407
retirado                    0
examen1                     6
examen2                    28
examen3                   407
final_sin_mejoramiento      3
final                       3
AP                          0
dtype: int64
retirados: 68
Null ex1 8
Null ex2 32
Num eq0 46
nombre                      0
matricula                   0
genero                      0
paralelo                    0
cod_carrera                 0
veces_tomadas               0
1er_proyecto                1
1er_sustent                 1
1er_lecciones               0
1er_calif_final             0
1er_exam_tema1              8
1er_exam_tema2              8
1er_exam_tema3              8
2do_proyecto                1
2do_sustent                 1
2do_lecciones               1
2do_calif_final             0
2do_exam_tema1             32
2do_exam_tema2             33
2do_exam_tema3             32
2do_exam_tema4             32
2do_exam_tema5             32
2do_exam_tema6             32
2do_exam_tema7             32
2do_exam_tema8             32
2do_exam_tema9             32
2do_exam_tema10            32
calif_final_practica        0
3er_proyecto              265
3er_calif_final             0
3er_exam_tema1            233
3er_exam_tema2            233
3er_exam_tema3            233
retirado                    0
examen1                     8
examen2                    33
examen3                   233
final_sin_mejoramiento      0
final                       0
AP                          0
dtype: int64
retirados: 64

In [108]:
df = dfs[0]
df[df.retirado]

,nombre,matricula,genero,paralelo,cod_carrera,veces_tomadas,1er_proyecto,1er_sustent,1er_lecciones,1er_calif_final,...,2do_exam_tema1,2do_exam_tema2,2do_exam_tema3,calif_final_practica,3er_proyecto,3er_calif_final,3er_exam_tema1,3er_exam_tema2,3er_exam_tema3,retirado
5,"Campozano Ramirez,Sergio Fabricio",198800310,M,1,LI-002,1,0.000,0.00,0.000000,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,True
9,"Chong Nieto,Belen Nathaly",201244384,F,1,LI-007,1,18.380,0.00,1.630000,17.000,...,0.0,0.0,0.0,34.0,0.0,0.0,0.0,0.0,0.0,True
11,"GONZALEZ ZAMBRANO,ANDRES ORLANDO",201700887,M,1,LI-005,1,9.000,0.00,1.870000,15.000,...,0.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,True
18,"NAVARRETE MATIAS,JUDY TATIANA",201711181,F,1,LI-004,2,11.000,0.00,3.500000,13.000,...,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,True
21,"Rugel Palacios,Ivan Josue",201208406,M,1,LI-007,1,16.880,0.00,3.500000,16.000,...,0.0,0.0,0.0,29.0,0.0,0.0,0.0,0.0,0.0,True
23,"Sangoquiza Chicaiza,Wilmer Marcelo",200625242,M,1,CI-007,1,17.500,0.00,3.730000,18.000,...,0.0,0.0,0.0,27.0,0.0,0.0,0.0,0.0,0.0,True
30,CAMPOVERDE CRESPO RICARDO ANDRES,201224004,M,2,CI-001,1,17.000,1.00,4.000000,32.000,...,NaN,NaN,NaN,40.0,NaN,NaN,NaN,NaN,NaN,True
34,DIAZ ZUÑIGA MICHELLE DEBORAH,201350121,F,2,LI-007,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,True
36,GUEVARA GAVILANEZ MICHAEL LENIN,201703162,M,2,CI-023,1,4.000,0.00,8.000000,29.000,...,NaN,NaN,NaN,27.0,NaN,NaN,NaN,NaN,NaN,True
38,LOZANO SANCHEZ JUAN CARLOS,201512477,M,2,CI-012,2,16.000,0.70,5.000000,34.000,...,NaN,NaN,NaN,58.0,NaN,NaN,NaN,NaN,NaN,True
42,MORALES CARDENAS MARIA FERNANDA,201503282,F,2,CI-025,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,True
47,PLAZA JOHNSON DAVID EDUARDO,201506768,M,2,LI-002,1,6.000,NaN,2.000000,10.000,...,NaN,NaN,NaN,38.0,NaN,NaN,NaN,NaN,NaN,True
49,RAMIREZ MATEO DOLLY DEL CARMEN,201407229,F,2,LI-001,1,7.000,0.50,3.000000,21.000,...,NaN,NaN,NaN,48.0,NaN,NaN,NaN,NaN,NaN,True
52,RUGEL LARA KEVIN MARCELO,201418060,M,2,CI-007,3,15.000,1.00,1.000000,21.000,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,True
54,SANCHEZ BUSTOS XAVIER ALEXANDER,201501625,M,2,LI-002,1,7.000,0.10,4.000000,22.000,...,NaN,NaN,NaN,38.0,NaN,NaN,NaN,NaN,NaN,True
57,VELEZ SUAREZ GALO RAUL,201314710,M,2,CI-015,1,1.000,0.10,3.000000,10.000,...,NaN,NaN,NaN,47.0,NaN,NaN,NaN,NaN,NaN,True
60,"Aguirre Loor,Genesis Lissette",201307338,F,3,LI-001,1,13.875,0.75,8.600000,74.000,...,NaN,NaN,NaN,92.0,NaN,NaN,NaN,NaN,NaN,True
65,"Baus Lomas,Luis Eduardo",201514357,M,3,LI-002,1,0.000,0.30,6.550000,36.000,...,NaN,NaN,NaN,60.0,NaN,NaN,NaN,NaN,NaN,True
68,"Burgos Arrieta,Sheyla Magdalena",201712064,F,3,LI-006,1,8.500,0.20,3.518750,20.000,...,NaN,NaN,NaN,62.0,NaN,NaN,NaN,NaN,NaN,True
69,"Cabello Sanchez,Jefferson Gabriel",201704830,M,3,CI-018,1,12.000,0.25,5.600000,35.000,...,NaN,NaN,NaN,47.0,NaN,NaN,NaN,NaN,NaN,True
70,"Campodonico Romero,Jesse Aaron",201701851,M,3,CI-017,1,11.350,0.15,5.068750,24.000,...,NaN,NaN,NaN,40.0,NaN,NaN,NaN,NaN,NaN,True
72,"Castillo Bravo,Erick Geovanny",201421123,M,3,CI-004,1,11.000,0.20,5.718750,23.000,...,NaN,NaN,NaN,33.0,NaN,NaN,NaN,NaN,NaN,True
74,"Ching Avalos,Siuling Viviana",201702685,F,3,CI-005,1,15.500,0.55,9.162500,91.000,...,NaN,NaN,NaN,98.0,NaN,NaN,NaN,NaN,NaN,True
75,"Chiquito Espinoza,Paola Mercedes",201704970,F,3,LI-009,1,10.900,0.10,4.512500,39.000,...,NaN,NaN,NaN,20.0,NaN,NaN,NaN,NaN,NaN,True
77,"Davalos Carrera,Josue Eulises",201707189,M,3,CI-013,1,15.500,0.60,7.250000,91.000,...,NaN,NaN,NaN,100.0,NaN,NaN,NaN,NaN,NaN,True
80,"Dume Gomez,Ariel Enrique",201707718,M,3,CI-022,1,14.000,0.45,6.250000,69.000,...,NaN,NaN,NaN,70.0,NaN,NaN,NaN,NaN,NaN,True
82,"Franco Vargas,Jean Carlos",201516658,M,3,CI-001,1,14.500,0.45,8.575000,56.000,...,NaN,NaN,NaN,75.0,NaN,NaN,NaN,NaN,NaN,True
83,"Goyes Perez,Aaron Orlando",201705852,M,3,CI-024,1,6.000,0.00,5.860417,19.000,...,NaN,NaN,NaN,67.0,NaN,NaN,NaN,NaN,NaN,True
84,"Gusqui Macas,Wilson Manuel",201403499,M,3,CI-017,1,9.000,NaN,2.343750,15.000,...,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,True
86,"Kuonqui Fernandez,Ana Sofia",201706421,F,3,CI-011,1,14.050,0.45,6.437500,59.000,...,NaN,NaN,NaN,82.0,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949,PIZA FIGUEROA JOSELINE YAJAIRA,201262067,F,41,CI-005,1,5.000,0.00,2.140000,10.790,...,NaN,NaN,NaN,26.0,NaN,NaN,NaN,NaN,NaN,True
957,ZAMBRANO SOTOMAYOR ANDREI PATRICIO,201513102,M,41,CI-012,1,16.030,0.80,7.970000,38.750,...,NaN,NaN,NaN,36.6,NaN,NaN,NaN,NaN,NaN,True
963,CHANCAY PIN EDISON RICARDO,200534469,M,42,LI-007,1,0.000,NaN,5.730000,7.000,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,True
965,DAVILA ALVARADO MARIA BELEN,201505112,F,42,CI-002,1,10.000,NaN,3.550000,22.000,...,NaN,NaN,NaN,27.0,NaN,NaN,NaN,NaN,NaN,True
970,HAGA MOREIRA ANGELO WLADIMIR,201222104,M,42,CI-005,1,13.000,0.20,6.330000,37.000,...,NaN,NaN,NaN,58.0,NaN,NaN,NaN,NaN,NaN,True
971,LERQUE CARVAJAL LUIS EMILIO,201516149,M,42,CI-020,1,11.000,0.30,8.950000,29.000,...,NaN,NaN,NaN,60.0,NaN,NaN,NaN,NaN,NaN,True
984,"Anton Solorzano,Harry Fabian",200820488,M,44,LI-002,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
985,"AREVALO MITE,FRANK ALEXANDER",201314339,M,44,CI-020,2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
992,"GALARZA NOBOA,ERICK ANDRE",201511987,M,44,CI-020,2,20.000,0.60,4.300000,24.750,...,NaN,NaN,NaN,36.0,NaN,NaN,NaN,NaN,NaN,True
996,"MAX TOLEDO,KALOH CRISTIAN",201613189,M,44,CI-001,1,0.000,0.00,1.200000,5.250,...,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,True
1004,"TENE BERMEO,ALEX ANDRES",201308317,M,44,LI-002,1,0.000,0.00,NaN,0.000,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,True
1008,"Villamar Trivino,Kerly Alexandra",201237990,F,44,CI-005,1,0.000,0.00,1.900000,3.625,...,NaN,NaN,NaN,51.0,NaN,NaN,NaN,NaN,NaN,True
1009,"YANEZ CHERREZ,DANIEL JESUS",201516395,M,44,CI-003,1,16.800,0.20,NaN,6.250,...,NaN,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,True
1010,"YUNGAN PILATAXI,FABIAN EDISON",201600988,M,44,CI-020,1,12.800,0.00,4.100000,5.750,...,NaN,NaN,NaN,53.0,NaN,NaN,NaN,NaN,NaN,True
1012,"Zambrano Sanchez,Nilson Stalin",200905024,M,44,CI-004,1,12.560,0.20,3.500000,9.550,...,NaN,NaN,NaN,75.0,NaN,NaN,NaN,NaN,NaN,True
1018,ANGULO RUELA ANDY BRYAN,201515993,M,18,CI-002,1,7.410,0.35,5.600000,23.000,...,NaN,NaN,NaN,59.0,NaN,NaN,NaN,NaN,NaN,True
1034,CLEMENTE VARGAS MIRELLA PAULETTE,201418138,F,18,LI-007,1,1.140,0.00,2.400000,4.000,...,NaN,NaN,NaN,23.0,NaN,NaN,NaN,NaN,NaN,True
1035,COQUE GONZALEZ BRYAN ANTHONY,201701398,M,18,CI-004,1,11.710,0.55,8.130000,30.000,...,NaN,NaN,NaN,26.0,NaN,NaN,NaN,NaN,NaN,True
1052,GONZALEZ YAGUAL DANIA GRACIELA,201511771,F,18,CI-011,1,1.000,0.00,1.800000,4.000,...,NaN,NaN,NaN,13.0,NaN,NaN,NaN,NaN,NaN,True
1053,GOROSTIZA LORENTY SULEYMA NARCISA,201700143,F,18,LI-001,1,11.830,0.50,8.550000,39.000,...,NaN,NaN,NaN,37.0,NaN,NaN,NaN,NaN,NaN,True
1065,LOOR BORBOR KEVIN ALBERTO,201612538,M,18,CI-009,1,8.160,0.35,6.050000,28.000,...,NaN,NaN,NaN,45.0,NaN,NaN,NaN,NaN,NaN,True
1066,LOOR MORALES CINTHYA REBECA,201506485,F,18,LI-002,1,6.380,0.30,4.880000,22.000,...,NaN,NaN,NaN,75.0,NaN,NaN,NaN,NaN,NaN,True
1101,SORIA VARGAS SAMANTHA IVONNE,201021375,F,18,CI-002,1,4.110,0.45,3.530000,18.000,...,NaN,NaN,NaN,28.0,NaN,NaN,NaN,NaN,NaN,True
1106,TORRES NEIRA JOSE MIGUEL,201603057,M,18,CI-007,1,7.650,0.50,5.950000,28.000,...,NaN,NaN,NaN,23.0,NaN,NaN,NaN,NaN,NaN,True
1110,VASQUEZ MACIAS MARIO RONALDO,201612140,M,18,CI-014,1,16.600,1.00,4.250000,32.000,...,NaN,NaN,NaN,56.0,NaN,NaN,NaN,NaN,NaN,True
1119,CHÓEZ CAJAMARCA DIANA LORENA,201127484,F,29,LI-007,1,6.620,0.20,6.430000,24.000,...,NaN,NaN,NaN,65.0,NaN,NaN,NaN,NaN,NaN,True
1123,FERNANDEZ COCA JUSTIN FIORELLA,201503535,F,29,CI-017,2,10.810,0.50,9.630000,36.000,...,NaN,NaN,NaN,24.0,NaN,NaN,NaN,NaN,NaN,True
1126,HIDALGO PALMA CINTHIA GABRIELA,201502978,F,29,LI-007,1,17.130,0.90,5.200000,37.000,...,NaN,NaN,NaN,35.0,NaN,NaN,NaN,NaN,NaN,True
1128,JARAMILLO GARCIA CHRISTOPHER ANDRES,201516267,M,29,CI-024,1,9.560,0.50,7.350000,28.000,...,NaN,NaN,NaN,61.0,NaN,NaN,NaN,NaN,NaN,True
1134,PARRAGA PEREZ MILENY CAROLINA,201600822,F,29,CI-003,1,9.960,0.50,4.630000,35.000,...,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,NaN,True

In [109]:
def calcular_notas(notas):
    notas["examen1"] = notas[notas.columns[notas.columns.str.contains("1er_exam_tema")]].sum(axis=1, skipna=False)
    notas["examen2"] = notas[notas.columns[notas.columns.str.contains("2do_exam_tema")]].sum(axis=1, skipna=False)
    notas["examen3"] = notas[notas.columns[notas.columns.str.contains("3er_exam_tema")]].sum(axis=1, skipna=False)
    notas["final_sin_mejoramiento"] = 0.2*notas.calif_final_practica + 0.80*(notas[["1er_calif_final", "2do_calif_final"]].mean(axis=1, skipna=False))
    notas["3er_calif_final"] = notas["3er_calif_final"].fillna(0)
    finales = notas[["1er_calif_final", "2do_calif_final", "3er_calif_final"]].values
    notas["final"] = (np.sort(finales, axis=1)[:, 1:].mean(1))*0.8 + 0.2*notas.calif_final_practica
    notas["AP"] = notas.final >= 60

In [110]:
for df in dfs:
    calcular_notas(df)

In [111]:
for df in dfs:
    print(df.AP.value_counts())

True     619
False    523
Name: AP, dtype: int64
True     849
False    369
Name: AP, dtype: int64
True     537
False    406
Name: AP, dtype: int64

In [141]:
for i, filename in enumerate(("2017_2T", "2018_1T", "2018_2T")):
    dfs[i].to_csv("modificados/"+filename+".csv", index=False, sep=";")

In [88]:
!ls

2017_2T.csv	  2017II.csv   2018I.csv     README.md
2017-I.csv	  2018_1T.csv  2018II.csv    Untitled.ipynb
2017II-2018I.csv  2018_2T.csv  carreras.csv

In [140]:
df = dfs[2]
retirados = df[df.retirado]
print(len(retirados))
ret_ap = retirados[retirados.AP]
print(len(ret_ap))

64
0

In [12]:
df_2017 = pd.read_csv("2017-I.csv", sep=";")
df_2017.head()

,nombre,matricula,genero,paralelo,cod_carrera,practica_cantidad_talleres,practica_calificacion_final,teoria_1erparcial_calificacion_sustentacion,teoria_1erparcial_calificacion_proyecto,teoria_1erparcial_cantidad_actividades,...,teoria_2doparcial_examen_tema3,teoria_2doparcial_examen,teoria_2doparcial_calificacion_final,teoria_mejoramiento_calificacion_proyecto,teoria_mejoramiento_calificacion_sustentacion,teoria_mejoramiento_examen_tema1,teoria_mejoramiento_examen_tema2,teoria_mejoramiento_examen_tema3,teoria_mejoramiento_examen,teoria_mejoramiento_calificacion_final
0,AGUIRRE VINCES DAILY DAISY,201600780,F,2,CI-003,14.0,80,"0,5",12,12.0,...,0,2,3,0,0,0,0,0,0,0
1,ALCIVAR PARDO DOMENICA PAOLA,201700200,F,2,LI-002,14.0,45,"0,4",5,12.0,...,0,0,0,0,0,0,0,0,0,0
2,ANRRANGO TIBANQUIZA ALEX XAVIER,201707650,M,2,CI-022,14.0,93,1,20,12.0,...,5,71,81,25,1,0,0,0,0,25
3,ASANZA QUEZADA RONALD EMILIO,201613635,M,2,CI-003,14.0,94,1,20,12.0,...,10,70,81,0,0,0,0,0,0,0
4,BRAVO LIMA ALEX EDUARDO,201604584,M,2,CI-017,14.0,78,1,19,12.0,...,5,83,86,21,1,0,0,0,0,21

In [13]:
df_2017.columns

Index(['nombre', 'matricula', 'genero', 'paralelo', 'cod_carrera',
       'practica_cantidad_talleres', 'practica_calificacion_final',
       'teoria_1erparcial_calificacion_sustentacion',
       'teoria_1erparcial_calificacion_proyecto',
       'teoria_1erparcial_cantidad_actividades',
       'teoria_1erparcial_examen_tema1', 'teoria_1erparcial_examen_tema2',
       'teoria_1erparcial_examen_tema3', 'teoria_1erparcial_examen',
       'teoria_1erparcial_calificacion_final',
       'teoria_2doparcial_calificacion_proyecto',
       'teoria_2doparcial_calificacion_sustentacion',
       'teoria_2doparcial_cantidad_actividades',
       'teoria_2doparcial_examen_tema1', 'teoria_2doparcial_examen_tema2',
       'teoria_2doparcial_examen_tema3', 'teoria_2doparcial_examen',
       'teoria_2doparcial_calificacion_final',
       'teoria_mejoramiento_calificacion_proyecto',
       'teoria_mejoramiento_calificacion_sustentacion',
       'teoria_mejoramiento_examen_tema1', 'teoria_mejoramiento_examen_tema2',
       'teoria_mejoramiento_examen_tema3', 'teoria_mejoramiento_examen',
       'teoria_mejoramiento_calificacion_final'],
      dtype='object')

In [23]:
df_2017.isnull().sum()

nombre                                             0
matricula                                          0
genero                                             0
paralelo                                           0
cod_carrera                                        0
practica_cantidad_talleres                        89
practica_calificacion_final                        0
teoria_1erparcial_calificacion_sustentacion        0
teoria_1erparcial_calificacion_proyecto            0
teoria_1erparcial_cantidad_actividades            89
teoria_1erparcial_examen_tema1                     8
teoria_1erparcial_examen_tema2                     8
teoria_1erparcial_examen_tema3                     9
teoria_1erparcial_examen                           0
teoria_1erparcial_calificacion_final               0
teoria_2doparcial_calificacion_proyecto            4
teoria_2doparcial_calificacion_sustentacion        4
teoria_2doparcial_cantidad_actividades            89
teoria_2doparcial_examen_tema1                    55
teoria_2doparcial_examen_tema2                    55
teoria_2doparcial_examen_tema3                    55
teoria_2doparcial_examen                           0
teoria_2doparcial_calificacion_final               0
teoria_mejoramiento_calificacion_proyecto        341
teoria_mejoramiento_calificacion_sustentacion    471
teoria_mejoramiento_examen_tema1                 384
teoria_mejoramiento_examen_tema2                 384
teoria_mejoramiento_examen_tema3                 384
teoria_mejoramiento_examen                         7
teoria_mejoramiento_calificacion_final             0
dtype: int64

In [15]:
df_2017["teoria_mejoramiento_calificacion_final"] = df_2017.teoria_mejoramiento_calificacion_final.fillna(0)

In [21]:
not_modify = ["nombre", "matricula", "genero", "paralelo", "cod_carrera", "practica_cantidad_talleres",
             "teoria_2doparcial_cantidad_actividades"]
for col in df_2017.columns:
        if col not in not_modify:
            print(col)
            df_2017[col] = df_2017[col].astype(str)
            df_2017[col] = df_2017[col].str.replace(',', '.')
            df_2017[col] = df_2017[col].str.replace('-', '0')
            df_2017[col] = df_2017[col].astype(float)
#df_2017["teoría_mejoramiento_calificacion_final"] = df_2017.teoria_mejoramiento_calificacion_final.astype(float)

practica_calificacion_final
teoria_1erparcial_calificacion_sustentacion
teoria_1erparcial_calificacion_proyecto
teoria_1erparcial_cantidad_actividades
teoria_1erparcial_examen_tema1
teoria_1erparcial_examen_tema2
teoria_1erparcial_examen_tema3
teoria_1erparcial_examen
teoria_1erparcial_calificacion_final
teoria_2doparcial_calificacion_proyecto
teoria_2doparcial_calificacion_sustentacion
teoria_2doparcial_examen_tema1
teoria_2doparcial_examen_tema2
teoria_2doparcial_examen_tema3
teoria_2doparcial_examen
teoria_2doparcial_calificacion_final
teoria_mejoramiento_calificacion_proyecto
teoria_mejoramiento_calificacion_sustentacion
teoria_mejoramiento_examen_tema1
teoria_mejoramiento_examen_tema2
teoria_mejoramiento_examen_tema3
teoria_mejoramiento_examen
teoria_mejoramiento_calificacion_final

In [22]:
df_2017.dtypes

nombre                                            object
matricula                                          int64
genero                                            object
paralelo                                           int64
cod_carrera                                       object
practica_cantidad_talleres                       float64
practica_calificacion_final                      float64
teoria_1erparcial_calificacion_sustentacion      float64
teoria_1erparcial_calificacion_proyecto          float64
teoria_1erparcial_cantidad_actividades           float64
teoria_1erparcial_examen_tema1                   float64
teoria_1erparcial_examen_tema2                   float64
teoria_1erparcial_examen_tema3                   float64
teoria_1erparcial_examen                         float64
teoria_1erparcial_calificacion_final             float64
teoria_2doparcial_calificacion_proyecto          float64
teoria_2doparcial_calificacion_sustentacion      float64
teoria_2doparcial_cantidad_actividades           float64
teoria_2doparcial_examen_tema1                   float64
teoria_2doparcial_examen_tema2                   float64
teoria_2doparcial_examen_tema3                   float64
teoria_2doparcial_examen                         float64
teoria_2doparcial_calificacion_final             float64
teoria_mejoramiento_calificacion_proyecto        float64
teoria_mejoramiento_calificacion_sustentacion    float64
teoria_mejoramiento_examen_tema1                 float64
teoria_mejoramiento_examen_tema2                 float64
teoria_mejoramiento_examen_tema3                 float64
teoria_mejoramiento_examen                       float64
teoria_mejoramiento_calificacion_final           float64
dtype: object

In [24]:
def calcular_notas(notas):
    notas["final_sin_mejoramiento"] = 0.2*notas.practica_calificacion_final + 0.80*(notas[["teoria_1erparcial_calificacion_final", "teoria_2doparcial_calificacion_final"]].mean(axis=1, skipna=False))
    finales = notas[["teoria_1erparcial_calificacion_final", "teoria_2doparcial_calificacion_final", "teoria_mejoramiento_calificacion_final"]].values
    notas["final"] = (np.sort(finales, axis=1)[:, 1:].mean(1))*0.8 + 0.2*notas.practica_calificacion_final
    notas["AP"] = notas.final >= 60

In [25]:
calcular_notas(df_2017)

In [28]:
df_2017.AP.value_counts(normalize=True)

True     0.619008
False    0.380992
Name: AP, dtype: float64

In [36]:
carreras = pd.read_csv("carreras_full.csv")

In [37]:
def cod_to_carrera(x):
    carrera = carreras[carreras.cod_carrera == x["cod_carrera"]]
    if len(carrera) != 0:
        return carrera.iloc[0, 1]
    #elif x["paralelo"] in (11, 14):
    #    return x["cod_carrera"]
    else:
        return "UNK"

In [38]:
df = df_2017
df["carrera"] = df.apply(cod_to_carrera, axis=1)
df[df["carrera"] == "UNK"]

Empty DataFrame
Columns: [nombre, matricula, genero, paralelo, cod_carrera, practica_cantidad_talleres, practica_calificacion_final, teoria_1erparcial_calificacion_sustentacion, teoria_1erparcial_calificacion_proyecto, teoria_1erparcial_cantidad_actividades, teoria_1erparcial_examen_tema1, teoria_1erparcial_examen_tema2, teoria_1erparcial_examen_tema3, teoria_1erparcial_examen, teoria_1erparcial_calificacion_final, teoria_2doparcial_calificacion_proyecto, teoria_2doparcial_calificacion_sustentacion, teoria_2doparcial_cantidad_actividades, teoria_2doparcial_examen_tema1, teoria_2doparcial_examen_tema2, teoria_2doparcial_examen_tema3, teoria_2doparcial_examen, teoria_2doparcial_calificacion_final, teoria_mejoramiento_calificacion_proyecto, teoria_mejoramiento_calificacion_sustentacion, teoria_mejoramiento_examen_tema1, teoria_mejoramiento_examen_tema2, teoria_mejoramiento_examen_tema3, teoria_mejoramiento_examen, teoria_mejoramiento_calificacion_final, final_sin_mejoramiento, final, AP, carrera]
Index: []

[0 rows x 34 columns]

In [39]:
df.to_csv("./modificados/2017-1T.csv", sep=";", index=False)